changelog:
  categories:
    - title: Features
      labels:
        - feature
        - enhancement
        - feat

    - title: Fixes
      labels:
        - fix
        - bug

    - title: Documentation
      labels:
        - documentation
        - docs

    - title: Test
      labels:
        - test

    - title: Other
      labels:
        - "*"
