name: PR-title linting

on: pull_request

jobs:
  lint: 
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        uses: dreampulse/action-lint-pull-request-title@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
